name: FredMatthews
favicon: null
layout_spectrum: 0
typography_spectrum: 0.615709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#152350'
    - '#2393d2'
    - '#d7f7ea'
    - '#e6b5b1'
    - '#d17776'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
